name: CD - Continuous Deployment

on:
  workflow_run:
    workflows: ["CI - Continuous Integration"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: angular-build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Fix esbuild permissions
      - name: Fix esbuild permissions
        run: |
          find node_modules/@esbuild -name "esbuild" -type f -exec chmod +x {} \;
          find node_modules/esbuild/bin -name "esbuild" -type f -exec chmod +x {} \; 2>/dev/null || true

      - name: Install Angular CLI globally
        run: npm install -g @angular/cli

      - name: Add Angular CLI GitHub Pages
        run: |
          if [ ! -f "angular.json" ] || ! grep -q "angular-cli-ghpages" angular.json; then
            ng add angular-cli-ghpages --skip-confirmation
          fi

      - name: Deploy to GitHub Pages
        run: ng deploy --base-href=https://sajjadranasariya.github.io/ng-test-app/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
